# Generated by Django 4.1 on 2022-08-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_useer_id_usercart_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='prodcut',
            new_name='product',
        ),
    ]
