# Generated by Django 4.1 on 2022-08-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_prodcut_usercart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_image',
            new_name='product_image',
        ),
    ]
